# Generated by Django 3.2.12 on 2022-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_app', '0003_auto_20220316_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/partners'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/pdf_files'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/resumes_images'),
        ),
    ]
